"""
Generate exchange mappings from Bloomberg CSV.

Reads Bloomberg-Exchange-Code-to-MIC-Mapping CSV and generates
Python code for ExchangeMapping objects, skipping incomplete rows.
"""

import csv
import sys
from pathlib import Path
from typing import List, Optional


def is_row_valid(row: List[str]) -> bool:
    """
    Check if row has all required fields populated.

    Args:
        row: CSV row as list of strings

    Returns:
        True if all required fields are non-empty
    """
    if len(row) < 8:
        return False

    # Required columns: MIC (0), MIC EXCHANGE NAME (2), EQUITY EXCH CODE (4),
    # Composite Code (6), ISO COUNTRY (7)
    required_indices = [0, 2, 4, 6, 7]

    for idx in required_indices:
        if idx >= len(row) or not row[idx].strip():
            return False

    return True


def clean_field(value: str) -> str:
    """
    Clean field value for Python code generation.

    Args:
        value: Raw CSV field value

    Returns:
        Cleaned string suitable for Python code
    """
    # Remove quotes and extra whitespace
    cleaned = value.strip().strip('"').strip("'")
    # Escape quotes in the value
    cleaned = cleaned.replace('"', '\\"')
    return cleaned


def generate_mapping_code(row: List[str]) -> Optional[str]:
    """
    Generate ExchangeMapping constructor call from CSV row.

    Args:
        row: CSV row as list of strings

    Returns:
        Python code string or None if row is invalid
    """
    if not is_row_valid(row):
        return None

    mic = clean_field(row[0])
    exchange_name = clean_field(row[2])
    bloomberg_regional_code = clean_field(row[4])
    bloomberg_composite_code = clean_field(row[6])
    country_code = clean_field(row[7])

    return (
        f'    ExchangeMapping(\n'
        f'        mic="{mic}",\n'
        f'        exchange_name="{exchange_name}",\n'
        f'        bloomberg_regional_code="{bloomberg_regional_code}",\n'
        f'        bloomberg_composite_code="{bloomberg_composite_code}",\n'
        f'        country_code="{country_code}",\n'
        f'    ),'
    )


def main():
    """Generate exchange mappings file from CSV."""
    project_root = Path(__file__).parent.parent
    csv_path = project_root / "Bloomberg-Exchange-Code-to-MIC-Mapping (1).csv"
    output_path = project_root / "src/stock_friend/data/exchange_mappings.py"

    if not csv_path.exists():
        print(f"Error: CSV file not found at {csv_path}")
        sys.exit(1)

    # Create output directory if needed
    output_path.parent.mkdir(parents=True, exist_ok=True)

    mappings: List[str] = []
    skipped_count = 0

    print(f"Reading CSV from: {csv_path}")

    with open(csv_path, "r", encoding="utf-8-sig") as f:
        reader = csv.reader(f)
        next(reader)  # Skip header row

        for line_num, row in enumerate(reader, start=2):
            mapping_code = generate_mapping_code(row)
            if mapping_code:
                mappings.append(mapping_code)
            else:
                skipped_count += 1

    print(f"Processed {len(mappings)} valid mappings")
    print(f"Skipped {skipped_count} incomplete rows")

    # Generate Python file
    output_content = f'''"""
Exchange mappings generated from Bloomberg MIC codes.

Auto-generated by scripts/generate_exchange_mappings.py
DO NOT EDIT MANUALLY - regenerate using the script.
"""

from stock_friend.models.symbol import ExchangeMapping

# All valid exchange mappings from Bloomberg CSV
EXCHANGE_MAPPINGS = [
{chr(10).join(mappings)}
]
'''

    with open(output_path, "w") as f:
        f.write(output_content)

    print(f"Generated mappings file: {output_path}")
    print(f"Total mappings: {len(mappings)}")


if __name__ == "__main__":
    main()
